name:
  Build Document
description:
  Build a static document using MkDocs.

runs:
  using: "composite"
  steps:
    - name: Install Requirements
      shell: bash
      run: |
        pip install -r requirements.txt
    - name: Build Document using MkDocs
      shell: bash
      run: |
        mkdocs build
