name: Build Docker Image
on:
  push:
  workflow_dispatch:


jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repository
       uses: actions/checkout@v3
       with:
         lfs: true

     - name: Setup Python 3.9
       uses: actions/setup-python@v3
       with:
         python-version: 3.9

     - name: Build using docker-compose
       run: |
         docker-compose build

  build-database:
    needs: build-image
    runs-on: ubuntu-latest

    steps:
      - name: Launch a database process
        run: |
          docker-compose up -d

      - name: Initialize the database
        run: |
          make initialize
