name: Build Document with MkDocs
on:
  push:
  pull_request:


jobs:
  build-mkdocs:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3
     - name: Setup Python 3.9
       uses: actions/setup-python@v3
       with:
         python-version: 3.9

     - name: Build Document
       uses: ./.github/actions/build_mkdocs
